name: learn github-actions
on: 
  push:
    branches:  [ main ]
  pull_request:
    branches:  [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name:  Run one line script
        run:  echo Hello RT!

      - name:  Run multi line script
        run: | 
          echo What is in this directory?
          ls -a
          echo Is Java installed
          java -version
          echo Is Git installed?
          git --version
          echo What dev tools are installed?
          mvn --version
          gradle --version
          ant --version




          
