name: learn github-actions
on: 
  push:
    branches:  [ main ]
  pull_request:
    branches:  [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name:  Run one line script
        run:  echo Hello RT!

      - name:  Run multi line script
        run: | 
          echo 1-What is in this directory?
          ls -a
          echo
          echo 2- Is Java installed
          java -version
          echo
          echo 3- Is Git installed?
          git --version
          echo
          echo 4- What dev tools are installed?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 5- Where is the Anroid root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 6- Where is Selenium jars?
          echo $SELENIUM_JAR_PATH
          echo
          echo 7- What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo 
          echo 8 -Who is running this script
          whoami
          echo
          echo 9- How is the disk laid out?
          df
          echo
          echo 10- What environment evariables are available?
          env
          
        
          




          
