name: learn github-actions
on: 
  push:
    branches:  [ main ]
  pull_request:
    branches:  [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name:  Run one line script
        run:  sh ./github-actions-script.sh

      - name:  Run multi line script
        run: | 
          echo deleted bash commands below and moved it to script file
          echo Here is what in the folder
          ls -a
          
